// Trusted bilingual article copy; no remote HTML.
(function(){'use strict';const copy={
  "en": {
    "status": "Development update",
    "date": "October 6, 2026",
    "title": "A new chapter.<br><em>Your career.</em>",
    "lede": "DeckBall 4.0 brings a new look, clearer match decisions and more life beyond the pitch. Built around the feedback of the people already playing.",
    "downloads": "Downloads",
    "reviews": "Google Play reviews",
    "rating": "Google Play rating",
    "snapshot": "Community snapshot · October 6, 2026",
    "introLabel": "FROM 3.9 TO 4.0",
    "introTitle": "Making the whole career feel connected.",
    "intro1": "A football career is more than the final score. It is the card you risk, the team you grow with, the people you meet and the stories that follow you off the pitch. For 4.0, the goal was to bring all of that closer together.",
    "intro2": "Your feedback shaped this update: confusing actions, repeated conversations, inconsistent artwork and weeks that could get stuck. Alongside the visual overhaul, the everyday parts of a career needed attention.",
    "jump1": "Career",
    "jump2": "Matches & cards",
    "jump3": "Football world",
    "jump4": "Off the pitch",
    "jump5": "Polish",
    "careerLabel": "01 / YOUR CAREER",
    "careerTitle": "A career hub with a clear next move.",
    "careerBody": "The career centre has a shared visual theme across its tabs. Your next fixture, energy, form and coach trust are easier to find. Team and league crests follow the same identity, so moving between screens feels like staying in one football world.",
    "careerMore": "Achievements and season goals have a stronger presentation, while career stories give each season more context. The match, training and social parts of your week sit closer together.",
    "careerCaption": "The new hub keeps the next match and your current condition in focus.",
    "matchLabel": "02 / MATCHES & CARDS",
    "matchTitle": "Play the card.<br>See the move.",
    "matchBody": "Card artwork was reviewed against the movement it is meant to show: rabona crosses, nutmegs, one-twos and goalkeeper actions. A card should tell you what you are about to attempt before you even read its name.",
    "matchMore": "The match commentary screen now carries the pitch action, with replays tied to what happened. Decision moments keep the footballer artwork and make room for your cards on smaller screens. The aim is to make each choice easier to read and its outcome easier to follow.",
    "matchCaption": "A one-two and the cards you can choose in a match situation.",
    "cardsCaption": "New cards have a clearer route into your active deck.",
    "worldLabel": "03 / THE FOOTBALL WORLD",
    "worldTitle": "Fresh lineups.<br>A shared identity.",
    "worldBody": "Starting club lists were checked and updated across 15 countries. New careers use 734 clubs across 37 league divisions. Team colours, country badges and league identities were brought into a more consistent visual system.",
    "worldMore": "Existing careers keep their own saved football world. The update refreshes starting memberships; it does not claim to reproduce every real-world playoff or tournament format.",
    "countries": "Countries",
    "clubs": "Starting clubs",
    "divisions": "League divisions",
    "worldCaption": "Country selection with a consistent badge style.",
    "lifeLabel": "04 / OFF THE PITCH",
    "lifeTitle": "People, not just profile cards.",
    "lifeBody": "Character portraits now have more individual styles, and relationship stories, dialogue and consequences received another pass. Team relationships and career events also give life outside a match more room to develop.",
    "lifeMore": "DeckTalk brings club accounts, sports media and fans into the same feed. More distinct profiles and a better-balanced follower curve help your reputation grow with your career.",
    "datingCaption": "Refreshed character portraits and relationship screens.",
    "socialCaption": "Club, press and fan reactions in DeckTalk.",
    "polishLabel": "05 / THE EVERYDAY DETAILS",
    "polishTitle": "An easier first week.<br>A smoother next season.",
    "polishIntro": "The quieter changes matter every time you open the game:",
    "fix1": "A guided visual tutorial shows you around the career screens. Returning players can also see the new tour once and choose to skip it.",
    "fix2": "Weekly progression fixes cover low-energy and injury situations, including weeks where resting has already been used.",
    "fix3": "Swipe fixes restore the connection between liking a character and starting a conversation.",
    "fix4": "Deck suggestions and card purchase feedback make it harder to forget a new card in your collection.",
    "fix5": "Audio handling and unused assets were cleaned up to reduce unnecessary work and keep the package lighter.",
    "thanksLabel": "ONE DEVELOPER. A SHARED JOURNEY.",
    "thanksTitle": "Thank you for sticking with DeckBall.",
    "thanksBody": "14,500 downloads and 117 Google Play reviews are a lot of people for a solo project. Every thoughtful review, bug report and screenshot helped decide what 4.0 should become. This update is a step toward making the game feel as complete as the careers you build in it.",
    "releaseNote": "4.0 is being prepared for release. These images are from the development build; the current Google Play version remains available while the update is readied.",
    "cta": "Play DeckBall on Google Play",
    "back": "All devlogs →",
    "metaTitle": "DeckBall 4.0 — A new chapter for your career | Clyrex Games",
    "metaDesc": "Inside DeckBall 4.0: a new career hub, refreshed cards and crests, match replays, relationship stories, DeckTalk and a guided tutorial. See the new game screens."
  },
  "tr": {
    "status": "Geliştirme günlüğü",
    "date": "6 Ekim 2026",
    "title": "Yeni bir sayfa.<br><em>Senin kariyerin.</em>",
    "lede": "DeckBall 4.0; yeni görünümü, daha anlaşılır maç kararları ve saha dışındaki hikâyeleriyle geliyor. Bu güncellemenin yönünü oyunu oynayanların geri bildirimleri belirledi.",
    "downloads": "İndirme",
    "reviews": "Google Play yorumu",
    "rating": "Google Play puanı",
    "snapshot": "Topluluk · 6 Ekim 2026",
    "introLabel": "3.9’DAN 4.0’A",
    "introTitle": "Kariyerin bütün parçalarını birleştirmek.",
    "intro1": "Futbol kariyeri son skordan ibaret değil. Risk alıp oynadığın kart, birlikte büyüdüğün takım, tanıştığın insanlar ve saha dışında seni takip eden hikâyeler de bunun parçası. 4.0’da hedef, bu parçaları birbirine daha iyi bağlamaktı.",
    "intro2": "Bu güncelleme sizin geri bildirimlerinizle şekillendi: anlaşılmayan hareketler, tekrarlayan sohbetler, birbiriyle uyuşmayan görseller ve ilerlemeyen haftalar. Görsel yenilenmeyle birlikte, kariyerin günlük akışına da el atmak gerekiyordu.",
    "jump1": "Kariyer",
    "jump2": "Maçlar ve kartlar",
    "jump3": "Futbol dünyası",
    "jump4": "Saha dışı",
    "jump5": "İyileştirmeler",
    "careerLabel": "01 / SENİN KARİYERİN",
    "careerTitle": "Bir sonraki adımın daha net.",
    "careerBody": "Kariyer merkezi ve sekmeleri ortak bir görsel temaya kavuştu. Sıradaki maçını, enerjini, formunu ve hocanın güvenini daha kolay görebiliyorsun. Takım ve lig armaları aynı görsel dili kullanıyor; ekran değiştirirken aynı futbol dünyasında kalıyorsun.",
    "careerMore": "Başarımlar ve sezon hedefleri daha belirgin bir sunuma kavuşurken kariyer hikâyeleri sezonlara yeni bir bağlam katıyor. Maç, antrenman ve sosyal hayat haftanın akışında birbirine daha yakın.",
    "careerCaption": "Yeni kariyer merkezi, sıradaki maçı ve oyuncunun durumunu öne çıkarıyor.",
    "matchLabel": "02 / MAÇLAR VE KARTLAR",
    "matchTitle": "Kartını oyna.<br>Hareketini gör.",
    "matchBody": "Kart çizimleri, anlatmaları gereken hareketlere göre tekrar incelendi: rabona ortaları, bacak arası çalımları, duvar pasları ve kaleci hamleleri. Kartın adı kadar görseli de ne yapacağını anlatmalı.",
    "matchMore": "Sahadaki aksiyon spiker ekranında yaşanıyor; tekrarlar maçta olanlara bağlanıyor. Karar anlarında futbolcu görselleri korunurken küçük ekranlarda kartlara daha fazla alan açılıyor. Amaç, hamleyi seçerken daha rahat okumak ve sonucunu daha iyi takip etmek.",
    "matchCaption": "Bir duvar pası ve maç pozisyonunda seçebileceğin kartlar.",
    "cardsCaption": "Yeni karttan aktif destene uzanan yol daha anlaşılır.",
    "worldLabel": "03 / FUTBOL DÜNYASI",
    "worldTitle": "Güncel kadrolar.<br>Ortak bir kimlik.",
    "worldBody": "15 ülkedeki başlangıç kulüp listeleri kontrol edilip güncellendi. Yeni kariyerler 37 lig bölümünde 734 kulüple başlıyor. Takım renkleri, ülke armaları ve lig kimlikleri daha tutarlı bir görsel sisteme taşındı.",
    "worldMore": "Mevcut kariyerler, kayıtlarındaki futbol dünyasını koruyor. Bu güncelleme başlangıç kulüp katılımlarını yeniliyor; bütün gerçek play-off ve turnuva formatlarını birebir uygulama iddiası taşımıyor.",
    "countries": "Ülke",
    "clubs": "Başlangıç kulübü",
    "divisions": "Lig bölümü",
    "worldCaption": "Ortak arma tarzıyla yenilenen ülke seçimi.",
    "lifeLabel": "04 / SAHA DIŞINDA",
    "lifeTitle": "Profil kartlarının ötesinde.",
    "lifeBody": "Karakter portreleri daha farklı görünümlere kavuştu. İlişki hikâyeleri, diyaloglar ve seçimlerin sonuçları yeniden ele alındı. Takım ilişkileri ve kariyer olayları da maçlar arasındaki hayatı zenginleştiriyor.",
    "lifeMore": "DeckTalk; kulüp hesaplarını, spor basınını ve taraftarları aynı akışta buluşturuyor. Daha farklı profiller ve dengelenen takipçi gelişimiyle itibarın kariyerinle birlikte büyüyor.",
    "datingCaption": "Yenilenen karakter portreleri ve ilişki ekranları.",
    "socialCaption": "DeckTalk’ta kulüp, basın ve taraftar tepkileri.",
    "polishLabel": "05 / GÜNLÜK AKIŞ",
    "polishTitle": "Daha kolay bir ilk hafta.<br>Daha akıcı bir sonraki sezon.",
    "polishIntro": "Küçük gibi görünen bu değişiklikler, oyunu her açtığında fark yaratıyor:",
    "fix1": "Görsel eğitim, kariyer ekranlarını adım adım tanıtıyor. Mevcut oyuncular da yeni turu bir kez görebilecek ve isterlerse kapatabilecek.",
    "fix2": "Düşük enerji ve sakatlık durumlarında hafta ilerletme düzeltildi; o hafta zaten dinlenilmiş olması da hesaba katılıyor.",
    "fix3": "Kaydırma düzeltmeleri, karakteri beğenme ile sohbet başlatma arasındaki bağlantıyı yeniden kuruyor.",
    "fix4": "Deste önerileri ve kart satın alma bildirimi, yeni kartını koleksiyonda unutmanı zorlaştırıyor.",
    "fix5": "Ses yönetimi ve kullanılmayan varlıklar elden geçirildi; gereksiz yük azaltılıp oyun paketi hafifletildi.",
    "thanksLabel": "TEK GELİŞTİRİCİ. BİRLİKTE BİR YOLCULUK.",
    "thanksTitle": "DeckBall’un yanında kaldığınız için teşekkürler.",
    "thanksBody": "14.500 indirme ve 117 Google Play yorumu, tek kişinin geliştirdiği bir proje için çok fazla insan demek. Her düşünülmüş yorum, hata bildirimi ve ekran görüntüsü 4.0’ın yönünü belirlemeye yardımcı oldu. Bu güncelleme, oyunun da kurduğunuz kariyerler kadar bütün hissettirmesi için bir adım.",
    "releaseNote": "4.0 yayına hazırlanıyor. Bu yazıdaki görseller geliştirme sürümünden; güncelleme hazırlanırken mevcut Google Play sürümü oynanmaya devam ediyor.",
    "cta": "DeckBall’u Google Play’de oyna",
    "back": "Tüm devloglar →",
    "metaTitle": "DeckBall 4.0 — Kariyerine yeni bir sayfa | Clyrex Games",
    "metaDesc": "DeckBall 4.0 geliştirme günlüğü: yeni kariyer merkezi, kartlar ve armalar, maç tekrarları, ilişkiler, DeckTalk ve görsel eğitim. Yeni oyun ekranlarını incele."
  }
};function apply(){const lang=window.I18N?.lang==='tr'?'tr':'en',c=copy[lang];document.querySelectorAll('[data-v40]').forEach(el=>{const k=el.dataset.v40;if(c[k]!==undefined)el.innerHTML=c[k];});document.querySelectorAll('[data-v40-image]').forEach(el=>{el.src='assets/images/deckball-v40/'+lang+'/'+el.dataset.v40Image+'.jpg';const captions={cover:'metaTitle',career:'careerCaption',match:'matchCaption',cards:'cardsCaption',world:'worldCaption',dating:'datingCaption',social:'socialCaption'};el.alt=c[captions[el.dataset.v40Image]]||el.alt;});document.title=c.metaTitle;document.querySelector('meta[name="description"]').content=c.metaDesc;document.querySelector('meta[property="og:title"]').content=c.metaTitle;document.querySelector('meta[property="og:description"]').content=c.metaDesc;document.querySelector('meta[property="og:image"]').content='https://clyrexgames.com/assets/images/deckball-v40/'+lang+'/cover.jpg';}window.addEventListener('langchange',apply);apply();})();
