// Trusted bilingual article copy; no remote HTML.
(function(){'use strict';const copy={
  "en": {
    "status": "4.0 is live",
    "date": "October 6, 2026",
    "title": "A new chapter.<br><em>Your career.</em>",
    "lede": "DeckBall 4.0 is live: a new look, clearer match decisions and personal stories beyond the pitch. Built around the feedback of the people already playing.",
    "downloads": "Downloads",
    "reviews": "Google Play reviews",
    "rating": "Google Play rating",
    "snapshot": "Community snapshot · October 6, 2026",
    "introLabel": "FROM 3.9 TO 4.0",
    "introTitle": "Making the whole career feel connected.",
    "intro1": "In 3.9, we worked on goalkeeper careers, performance-based transfers and relationships. 4.0 keeps those systems and adds more match situations, ongoing personal stories, season reviews and new tools for your career.",
    "intro2": "Below, the additions come first, followed by the screens and existing content that were reworked. Goalkeeper mode, DeckTalk, marriage and children were already in the game; 4.0 connects them more closely to the rest of your career.",
    "jump1": "Career",
    "jump2": "Matches & cards",
    "jump3": "Football world",
    "jump4": "Off the pitch",
    "jump5": "Polish",
    "careerLabel": "01 / YOUR CAREER",
    "careerTitle": "A career hub with a clear next move.",
    "careerBody": "The career centre has a shared visual theme across its tabs. Your next fixture, energy, form and coach trust are easier to find. Team and league crests follow the same identity, so moving between screens feels like staying in one football world.",
    "careerMore": "The achievement showcase presents the existing 28 badges with distinct frames, progress targets and earned notifications. New season goals and the Career Journal give you direction beyond winning the next match. Tapping an open bottom-bar tab again closes it.",
    "careerCaption": "The new hub keeps the next match and your current condition in focus.",
    "matchLabel": "02 / MATCHES & CARDS",
    "matchTitle": "Play the card.<br>See the move.",
    "matchBody": "Card artwork was reviewed against the movement it is meant to show: rabona crosses, nutmegs, one-twos and goalkeeper actions. A card should tell you what you are about to attempt before you even read its name.",
    "matchMore": "After you choose a card, its outcome plays on the live pitch in the commentary screen and the match continues. The action follows the real card result and score. Decision moments retain footballer artwork and keep three options accessible on smaller screens. A pass that creates a team goal earns an assist; a dribble does not automatically count as one.",
    "matchCaption": "A one-two and the cards you can choose in a match situation.",
    "cardsCaption": "New cards have a clearer route into your active deck.",
    "worldLabel": "03 / THE FOOTBALL WORLD",
    "worldTitle": "Fresh lineups.<br>A shared identity.",
    "worldBody": "Starting club lists were checked and updated across 15 countries. New careers use 734 clubs across 37 league divisions. Team colours, country badges and league identities were brought into a more consistent visual system.",
    "worldMore": "Starting memberships and European competition entries were updated; team colours and crests in the league screen share one source. The 734 clubs are the updated total, not the number of additions. Existing careers keep their own saved football world.",
    "countries": "Countries",
    "clubs": "Starting clubs",
    "divisions": "League divisions",
    "worldCaption": "Country selection with a consistent badge style.",
    "lifeLabel": "04 / OFF THE PITCH",
    "lifeTitle": "People, not just profile cards.",
    "lifeBody": "The six existing characters received more individual portraits and refreshed conversations. Date preferences, trust and time actually spent together shape relationship progress. Repeated gifts have less impact; high closeness alone does not guarantee exclusivity or an accepted proposal.",
    "lifeMore": "DeckTalk now includes club accounts using the in-game club’s crest, distinct media identities and varied fan portraits. Post variation reduces repetition. Follower growth is balanced around league visibility, minutes played and performance, rather than multiplying every week in lower leagues.",
    "datingCaption": "Refreshed character portraits and relationship screens.",
    "socialCaption": "Club, press and fan reactions in DeckTalk.",
    "polishLabel": "05 / THE EVERYDAY DETAILS",
    "polishTitle": "An easier first week.<br>A smoother next season.",
    "polishIntro": "The quieter changes matter every time you open the game:",
    "fix1": "A guided visual tutorial shows you around the career screens. Returning players can also see the new tour once and choose to skip it.",
    "fix2": "Weekly progression fixes cover low-energy and injury situations, including weeks where resting has already been used.",
    "fix3": "Swipe fixes restore the connection between liking a character and starting a conversation.",
    "fix4": "Deck suggestions and card purchase feedback make it harder to forget a new card in your collection.",
    "fix5": "Audio handling and unused assets were cleaned up to reduce unnecessary work and keep the package lighter.",
    "thanksLabel": "ONE DEVELOPER. A SHARED JOURNEY.",
    "thanksTitle": "Thank you for sticking with DeckBall.",
    "thanksBody": "14,500 downloads and 117 Google Play reviews are a lot of people for a solo project. Every thoughtful review, bug report and screenshot helped decide what 4.0 should become. This update is a step toward making the game feel as complete as the careers you build in it.",
    "releaseNote": "DeckBall 4.0 is available on Google Play. Existing players can update through the store; new players can start their career in 4.0.",
    "cta": "Download / update on Google Play",
    "back": "All devlogs →",
    "metaTitle": "DeckBall 4.0 — A new chapter for your career | Clyrex Games",
    "metaDesc": "From DeckBall 3.9 to 4.0: 24 match moments, ongoing career and team stories, Elif and Derya, personal relationships, awards night and refreshed game screens.",
    "newLabel": "ADDED IN 4.0",
    "newTitle": "Behind the new look,<br>there is more to play.",
    "newIntro": "Decisions that carry into the next week, teammates with their own concerns, and a season that leaves a story behind.",
    "new1Title": "From 9 generic situations to 24 match moments",
    "new1Body": "One-twos, cutbacks, escaping a press, interceptions, last-man cover and goalkeeper interventions are selected for your position. The same moment does not appear twice in one match. Teammate support and the opponent’s playing style affect your chances; turning a good pass into a goal also depends on the teammate finishing it.",
    "new2Title": "A Career Journal and five story paths",
    "new2Body": "The coach, selection competition, derby, media and transfer paths each have three chapters. Saying “I will work on it” is not enough: later chapters check your actual training, rest and match appearances. The journal keeps your promises and the outcomes of your last 12 stories.",
    "new3Title": "Beyond the dressing room",
    "new3Body": "The captain, young player, veteran and selection rival have personal concerns of their own. Four paths with 12 chapters: supporting a young teammate struggling with comments, or a captain carrying everyone’s problems. Bonds develop through real conversations and activities across different weeks.",
    "new4Title": "Two new people: Elif and Derya",
    "new4Body": "The partner roster grows from six to eight. Sound designer Elif’s studio project and Derya’s neighbourhood and city work shape their conversations. The two additions bring 20 main conversations. All eight partners now have 24 personal story chapters in total, with individual expectations and preferences.",
    "new5Title": "Relationships remember the next season",
    "new5Body": "Finding time together and making room for personal goals open new topics in later seasons. Broken promises or unwanted public posts can lead to a trust process. Gifts alone cannot build the relationship: attention across different weeks, attending dates and respecting boundaries matter.",
    "new6Title": "The echo of a public post",
    "new6Body": "A date photo, transfer rumour or controversial statement can start one of three four-chapter public stories. Your first reply is remembered in later weeks. A promise to answer on the pitch requires actual play and training; a rumour cannot create a transfer offer by itself.",
    "new7Title": "Season reviews and an awards night",
    "new7Body": "After your transfer decision, a three-stage ceremony presents your team result, trophies you actually won and personal performance. A season archive and trophy cabinet preserve that history. Outfield players and keepers are evaluated using their own statistics; the Golden Ball follows DeckBall’s in-game award conditions.",
    "new8Title": "A clearer first week and an easier deck setup",
    "new8Body": "The old daily “play a match / train once” guidance is replaced by an eight-step visual tutorial. Skip it or replay it in settings. Purchase receipts, deck suggestions and an eight-slot active deck layout help you bring a newly acquired card into your matches.",
    "renewedLabel": "REWORKED FOR 4.0",
    "renewedTitle": "Familiar systems, with a stronger presentation.",
    "renewedBody": "The career hub, main menu, match screens, card art, equipment, country and league crests now share a visual direction. All 159 existing major events were rewritten across eight languages; these are not 159 newly added events. Micro-event writing and 12 scene illustrations were refreshed too."
  },
  "tr": {
    "status": "4.0 yayında",
    "date": "6 Ekim 2026",
    "title": "Yeni bir sayfa.<br><em>Senin kariyerin.</em>",
    "lede": "DeckBall 4.0 yayında: yeni görünüm, daha anlaşılır maç kararları ve saha dışındaki kişisel hikâyeler artık oyunda. Bu güncellemenin yönünü oyunu oynayanların geri bildirimleri belirledi.",
    "downloads": "İndirme",
    "reviews": "Google Play yorumu",
    "rating": "Google Play puanı",
    "snapshot": "Topluluk · 6 Ekim 2026",
    "introLabel": "3.9’DAN 4.0’A",
    "introTitle": "Kariyerin bütün parçalarını birleştirmek.",
    "intro1": "3.9’da kaleci kariyeri, performansa bağlı transferler ve ilişkiler üzerinde çalışmıştık. 4.0 bu sistemleri koruyor; üzerine maç çeşitliliği, devam eden kişisel hikâyeler, sezon değerlendirmesi ve yeni kariyer araçları ekliyor.",
    "intro2": "Aşağıda önce bu sürümde eklenenleri, ardından yeniden ele alınan ekranları ve eski içerikleri bulabilirsin. Kaleci modu, DeckTalk, evlilik ve çocuk sahibi olma zaten oyundaydı; 4.0’ın yeniliği bunları kariyerin geri kalanıyla daha güçlü bağlamak.",
    "jump1": "Kariyer",
    "jump2": "Maçlar ve kartlar",
    "jump3": "Futbol dünyası",
    "jump4": "Saha dışı",
    "jump5": "İyileştirmeler",
    "careerLabel": "01 / SENİN KARİYERİN",
    "careerTitle": "Bir sonraki adımın daha net.",
    "careerBody": "Kariyer merkezi ve sekmeleri ortak bir görsel temaya kavuştu. Sıradaki maçını, enerjini, formunu ve hocanın güvenini daha kolay görebiliyorsun. Takım ve lig armaları aynı görsel dili kullanıyor; ekran değiştirirken aynı futbol dünyasında kalıyorsun.",
    "careerMore": "Başarım vitrini, mevcut 28 rozeti kendine özgü çerçeveler, ilerleme hedefleri ve kazanılma bildirimleriyle sunuyor. Yeni sezon hedefleri ve Kariyer Günlüğü, yalnızca maç kazanmanın ötesinde takip edebileceğin bir yön veriyor. Alt çubukta açık sekmeye tekrar dokunmak onu kapatıyor.",
    "careerCaption": "Yeni kariyer merkezi, sıradaki maçı ve oyuncunun durumunu öne çıkarıyor.",
    "matchLabel": "02 / MAÇLAR VE KARTLAR",
    "matchTitle": "Kartını oyna.<br>Hareketini gör.",
    "matchBody": "Kart çizimleri, anlatmaları gereken hareketlere göre tekrar incelendi: rabona ortaları, bacak arası çalımları, duvar pasları ve kaleci hamleleri. Kartın adı kadar görseli de ne yapacağını anlatmalı.",
    "matchMore": "Kartını seçtikten sonra hamlenin sonucu spiker ekranındaki canlı sahada oynanıyor ve maç devam ediyor. Saha akışı gerçek kart sonucu ve skorla eşleşiyor. Karar anlarında futbolcu görselleri korunuyor; küçük ekranlarda üç seçenek de erişilebilir kalıyor. Pasla gelen takım golü asist sayılıyor, çalımdan gelen takım golü otomatik asist yazmıyor.",
    "matchCaption": "Bir duvar pası ve maç pozisyonunda seçebileceğin kartlar.",
    "cardsCaption": "Yeni karttan aktif destene uzanan yol daha anlaşılır.",
    "worldLabel": "03 / FUTBOL DÜNYASI",
    "worldTitle": "Güncel kadrolar.<br>Ortak bir kimlik.",
    "worldBody": "15 ülkedeki başlangıç kulüp listeleri kontrol edilip güncellendi. Yeni kariyerler 37 lig bölümünde 734 kulüple başlıyor. Takım renkleri, ülke armaları ve lig kimlikleri daha tutarlı bir görsel sisteme taşındı.",
    "worldMore": "Başlangıç listeleri ve Avrupa kupası katılımları güncellendi; takım renkleri ve lig ekranındaki armalar ortak kaynaktan geliyor. 734 kulüp güncelleme sonrası toplam sayı; yeni eklenen kulüp sayısı değil. Mevcut kayıtlar kendi futbol dünyasını koruyor.",
    "countries": "Ülke",
    "clubs": "Başlangıç kulübü",
    "divisions": "Lig bölümü",
    "worldCaption": "Ortak arma tarzıyla yenilenen ülke seçimi.",
    "lifeLabel": "04 / SAHA DIŞINDA",
    "lifeTitle": "Profil kartlarının ötesinde.",
    "lifeBody": "Eski altı karakterin portreleri ve sohbetleri kişisel tarzlarına göre yenilendi. Buluşma tercihi, güven ve gerçekten birlikte geçirilen zaman ilişkinin ilerlemesini belirliyor. Tekrarlanan hediyelerin etkisi azalıyor; yüksek yakınlık tek başına ciddi ilişki veya teklif kabulü için yeterli değil.",
    "lifeMore": "DeckTalk’a gerçek oyun kulübünün armasıyla paylaşım yapan takım hesapları, belirgin medya kimlikleri ve farklı taraftar portreleri eklendi. Paylaşım çeşitliliği tekrarı azaltıyor. Takipçi artışı lig görünürlüğü, oynanan süre ve performansa göre dengelendi; alt ligde her hafta katlanarak büyümüyor.",
    "datingCaption": "Yenilenen karakter portreleri ve ilişki ekranları.",
    "socialCaption": "DeckTalk’ta kulüp, basın ve taraftar tepkileri.",
    "polishLabel": "05 / GÜNLÜK AKIŞ",
    "polishTitle": "Daha kolay bir ilk hafta.<br>Daha akıcı bir sonraki sezon.",
    "polishIntro": "Küçük gibi görünen bu değişiklikler, oyunu her açtığında fark yaratıyor:",
    "fix1": "Görsel eğitim, kariyer ekranlarını adım adım tanıtıyor. Mevcut oyuncular da yeni turu bir kez görebilir ve isterlerse kapatabilir.",
    "fix2": "Düşük enerji ve sakatlık durumlarında hafta ilerletme düzeltildi; o hafta zaten dinlenilmiş olması da hesaba katılıyor.",
    "fix3": "Kaydırma düzeltmeleri, karakteri beğenme ile sohbet başlatma arasındaki bağlantıyı yeniden kuruyor.",
    "fix4": "Deste önerileri ve kart satın alma bildirimi, yeni kartını koleksiyonda unutmanı zorlaştırıyor.",
    "fix5": "Ses yönetimi ve kullanılmayan varlıklar elden geçirildi; gereksiz yük azaltılıp oyun paketi hafifletildi.",
    "thanksLabel": "TEK GELİŞTİRİCİ. BİRLİKTE BİR YOLCULUK.",
    "thanksTitle": "DeckBall’un yanında kaldığınız için teşekkürler.",
    "thanksBody": "14.500 indirme ve 117 Google Play yorumu, tek kişinin geliştirdiği bir proje için çok fazla insan demek. Her düşünülmüş yorum, hata bildirimi ve ekran görüntüsü 4.0’ın yönünü belirlemeye yardımcı oldu. Bu güncelleme, oyunun da kurduğunuz kariyerler kadar bütün hissettirmesi için bir adım.",
    "releaseNote": "DeckBall 4.0 Google Play’de yayında. Mevcut oyuncular oyunu mağazadan güncelleyebilir; yeni oyuncular 4.0 ile kariyerine başlayabilir.",
    "cta": "Google Play’den indir / güncelle",
    "back": "Tüm devloglar →",
    "metaTitle": "DeckBall 4.0 — Kariyerine yeni bir sayfa | Clyrex Games",
    "metaDesc": "DeckBall 3.9’dan 4.0’a: 24 maç durumu, bağlı kariyer ve takım hikâyeleri, Elif ve Derya, kişisel ilişkiler, ödül gecesi ve yenilenen oyun ekranları.",
    "newLabel": "4.0 İLE EKLENENLER",
    "newTitle": "Yeni görünümün arkasında<br>yeni oynanabilir içerik var.",
    "newIntro": "Sadece bir görsel yenileme değil. Haftadan haftaya devam eden kararlar, takım arkadaşlarının kendi gündemi ve sezonun sonunda geride bırakabileceğin bir hikâye.",
    "new1Title": "9 genel durumdan 24 maç pozisyonuna",
    "new1Body": "Duvar pası, geriye çıkarılan top, presin içinden çıkış, pas kesme, son örtme ve kaleci çıkışı gibi durumlar pozisyonuna göre seçiliyor. Aynı durum bir maçta iki kez gelmiyor. Takım arkadaşının desteği ve rakibin oyun düzeni hamlenin ihtimalini etkiliyor; iyi bir pasın gole dönüşmesi artık bitiren arkadaşının kalitesine de bağlı.",
    "new2Title": "Kariyer Günlüğü ve beş hikâye hattı",
    "new2Body": "Hoca, forma rekabeti, derbi, medya ve transfer konuları üç bölümlük hikâyelere dönüştü. “Çalışacağım” demek yetmiyor: sonraki bölüm gerçekten yaptığın antrenmana, dinlenmeye ve oynadığın maça bakıyor. Günlük, verdiğin sözleri ve son 12 hikâyenin sonuçlarını saklıyor.",
    "new3Title": "Soyunma odasının dışında",
    "new3Body": "Kaptan, genç oyuncu, tecrübeli oyuncu ve forma rakibinin kendi kişisel meseleleri var. Dört hat, toplam 12 bölüm: kötü yorumlarla uğraşan gencin yanında olmak veya bütün yükü taşıyan kaptana destek vermek gibi. Yakınlaşma farklı haftalardaki gerçek sohbet ve etkinliklerle ilerliyor.",
    "new4Title": "İki yeni insan: Elif ve Derya",
    "new4Body": "Partner sayısı altıdan sekize çıktı. Ses tasarımcısı Elif’in stüdyo projesi, Derya’nın mahalle ve şehir çalışmaları kendi sohbetlerine yansıyor. İki yeni karakterle birlikte 20 ana konuşma eklendi. Sekiz partnerin tamamı için toplam 24 kişisel hikâye bölümü var; her birinin kendi beklentisi ve tercihleri bulunuyor.",
    "new5Title": "İlişkiler sonraki sezonu hatırlıyor",
    "new5Body": "Birlikte zaman bulmak ve kişisel hedeflere alan açmak, sonraki sezonlarda yeni konular açıyor. Tutulmayan sözler veya izinsiz paylaşımlar güven sürecine dönüşebiliyor. İlişki yalnızca hediye vererek ilerlemiyor: farklı haftalarda ilgi göstermek, buluşmaya katılmak ve sınırlarına saygı duymak gerekiyor.",
    "new6Title": "Bir paylaşımın yankısı",
    "new6Body": "Buluşma fotoğrafı, transfer söylentisi ve tartışmalı bir açıklama artık üç ayrı, dörder bölümlük kamuoyu hikâyesine dönüşebiliyor. İlk cevabın sonraki haftalarda hatırlanıyor. Sahada cevap verme sözünü gerçek maç ve çalışma tamamlıyor; söylenti tek başına transfer teklifi yaratmıyor.",
    "new7Title": "Sezon değerlendirmesi ve ödül gecesi",
    "new7Body": "Transfer kararından sonra üç aşamalı bir tören; takım sonucunu, gerçekten kazandığın kupaları ve kişisel performansını gösteriyor. Sezon arşivi ile kupa dolabı bu geçmişi tutuyor. Saha oyuncuları ve kaleciler kendi istatistikleriyle değerlendirilirken Altın Top, DeckBall’ın oyun içi koşullarına bağlı bir ödül olarak yer alıyor.",
    "new8Title": "Kariyere girmek ve desteyi kurmak daha kolay",
    "new8Body": "Eski günlük “bir maç oyna / antrenman yap” yönlendirmelerinin yerini sekiz adımlık görsel eğitim aldı. Turu kapatabilir veya ayarlardan tekrar açabilirsin. Kart satın alma sonrası makbuz, deste önerileri ve sekiz yuvalı aktif deste düzeni yeni kartını oyuna taşımanda yardımcı oluyor.",
    "renewedLabel": "YENİDEN ELE ALINANLAR",
    "renewedTitle": "Sevdiğin sistemler, daha güçlü bir sunumla.",
    "renewedBody": "Yeni kariyer merkezi, ana menü, maç ekranları, kart çizimleri, ekipman, ülke ve lig armaları ortak bir görsel dile taşındı. 159 mevcut büyük olayın metinleri sekiz dilde yeniden işlendi; bu sayı 159 yeni olay anlamına gelmiyor. Mikro olayların anlatımı ve 12 sahne görseli de yenilendi."
  }
};function apply(){const lang=window.I18N?.lang==='tr'?'tr':'en',c=copy[lang];document.querySelectorAll('[data-v40]').forEach(el=>{const k=el.dataset.v40;if(c[k]!==undefined)el.innerHTML=c[k];});document.querySelectorAll('[data-v40-image]').forEach(el=>{el.src='assets/images/deckball-v40/'+lang+'/'+el.dataset.v40Image+'.jpg';const captions={cover:'metaTitle',career:'careerCaption',match:'matchCaption',cards:'cardsCaption',world:'worldCaption',dating:'datingCaption',social:'socialCaption'};el.alt=c[captions[el.dataset.v40Image]]||el.alt;});document.title=c.metaTitle;document.querySelector('meta[name="description"]').content=c.metaDesc;document.querySelector('meta[property="og:title"]').content=c.metaTitle;document.querySelector('meta[property="og:description"]').content=c.metaDesc;document.querySelector('meta[property="og:image"]').content='https://clyrexgames.com/assets/images/deckball-v40/'+lang+'/cover.jpg';}window.addEventListener('langchange',apply);apply();})();
